#!/bin/bash

apt update -y
apt install lrzsz -y
apt install build-essential -y
curl https://sh.rustup.rs -sSf | sh
sh -c "$(curl -sSfL https://release.solana.com/v1.18.4/install)"
source .profile
cargo install ore-cli
